//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 07:15:13 PM CEST 
//


package UF4AAD.DAOsobre;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for databaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="databaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clientes" type="{}clientesType"/>
 *         &lt;element name="empleados" type="{}empleadosType"/>
 *         &lt;element name="facturas" type="{}facturasType"/>
 *         &lt;element name="catalogo" type="{}catalogoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "databaseType", propOrder = {
    "clientes",
    "empleados",
    "facturas",
    "catalogo"
})
public class DatabaseType {

    @XmlElement(required = true)
    protected ClientesType clientes;
    @XmlElement(required = true)
    protected EmpleadosType empleados;
    @XmlElement(required = true)
    protected FacturasType facturas;
    @XmlElement(required = true)
    protected CatalogoType catalogo;

    /**
     * Gets the value of the clientes property.
     * 
     * @return
     *     possible object is
     *     {@link ClientesType }
     *     
     */
    public ClientesType getClientes() {
        return clientes;
    }

    /**
     * Sets the value of the clientes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientesType }
     *     
     */
    public void setClientes(ClientesType value) {
        this.clientes = value;
    }

    /**
     * Gets the value of the empleados property.
     * 
     * @return
     *     possible object is
     *     {@link EmpleadosType }
     *     
     */
    public EmpleadosType getEmpleados() {
        return empleados;
    }

    /**
     * Sets the value of the empleados property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmpleadosType }
     *     
     */
    public void setEmpleados(EmpleadosType value) {
        this.empleados = value;
    }

    /**
     * Gets the value of the facturas property.
     * 
     * @return
     *     possible object is
     *     {@link FacturasType }
     *     
     */
    public FacturasType getFacturas() {
        return facturas;
    }

    /**
     * Sets the value of the facturas property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacturasType }
     *     
     */
    public void setFacturas(FacturasType value) {
        this.facturas = value;
    }

    /**
     * Gets the value of the catalogo property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogoType }
     *     
     */
    public CatalogoType getCatalogo() {
        return catalogo;
    }

    /**
     * Sets the value of the catalogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogoType }
     *     
     */
    public void setCatalogo(CatalogoType value) {
        this.catalogo = value;
    }

}
