//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 07:15:13 PM CEST 
//


package UF4AAD.DAOsobre;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for facturaType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="facturaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nif_cliente">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="48089748z"/>
 *               &lt;enumeration value="47091749l"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="id_producto">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="precio_unidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="precio_total" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="iva" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "facturaType", propOrder = {
    "nifCliente",
    "idProducto",
    "precioUnidad",
    "precioTotal",
    "iva"
})
public class FacturaType {

    @XmlElement(name = "nif_cliente", required = true)
    protected String nifCliente;
    @XmlElement(name = "id_producto", required = true)
    protected String idProducto;
    @XmlElement(name = "precio_unidad", required = true)
    protected String precioUnidad;
    @XmlElement(name = "precio_total", required = true)
    protected String precioTotal;
    @XmlElement(required = true)
    protected String iva;

    /**
     * Gets the value of the nifCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNifCliente() {
        return nifCliente;
    }

    /**
     * Sets the value of the nifCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNifCliente(String value) {
        this.nifCliente = value;
    }

    /**
     * Gets the value of the idProducto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdProducto() {
        return idProducto;
    }

    /**
     * Sets the value of the idProducto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdProducto(String value) {
        this.idProducto = value;
    }

    /**
     * Gets the value of the precioUnidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecioUnidad() {
        return precioUnidad;
    }

    /**
     * Sets the value of the precioUnidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecioUnidad(String value) {
        this.precioUnidad = value;
    }

    /**
     * Gets the value of the precioTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecioTotal() {
        return precioTotal;
    }

    /**
     * Sets the value of the precioTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecioTotal(String value) {
        this.precioTotal = value;
    }

    /**
     * Gets the value of the iva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIva() {
        return iva;
    }

    /**
     * Sets the value of the iva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIva(String value) {
        this.iva = value;
    }

}
