//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:02:46 PM CET 
//


package UF1AAD.ExamenUF1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SOLARSYSTEM_QNAME = new QName("", "SOLAR_SYSTEM");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SOLARSYSTEMType }
     * 
     */
    public SOLARSYSTEMType createSOLARSYSTEMType() {
        return new SOLARSYSTEMType();
    }

    /**
     * Create an instance of {@link PLANETSType }
     * 
     */
    public PLANETSType createPLANETSType() {
        return new PLANETSType();
    }

    /**
     * Create an instance of {@link PLANETType }
     * 
     */
    public PLANETType createPLANETType() {
        return new PLANETType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SOLARSYSTEMType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SOLAR_SYSTEM")
    public JAXBElement<SOLARSYSTEMType> createSOLARSYSTEM(SOLARSYSTEMType value) {
        return new JAXBElement<SOLARSYSTEMType>(_SOLARSYSTEM_QNAME, SOLARSYSTEMType.class, null, value);
    }

}
