//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.05 at 07:02:46 PM CET 
//


package UF1AAD.ExamenUF1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PLANETType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PLANETType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NAME">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Mercury"/>
 *               &lt;enumeration value="Venus"/>
 *               &lt;enumeration value="Earth"/>
 *               &lt;enumeration value="Mars"/>
 *               &lt;enumeration value="Jupiter"/>
 *               &lt;enumeration value="Saturn"/>
 *               &lt;enumeration value="Uranus"/>
 *               &lt;enumeration value="Neptune"/>
 *               &lt;enumeration value="Pluto"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DISTANCE">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="57.91"/>
 *               &lt;enumeration value="108.21"/>
 *               &lt;enumeration value="149.60"/>
 *               &lt;enumeration value="227.9"/>
 *               &lt;enumeration value="778.3"/>
 *               &lt;enumeration value="1428"/>
 *               &lt;enumeration value="2872"/>
 *               &lt;enumeration value="4498"/>
 *               &lt;enumeration value="5910"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RADIUS">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="2340"/>
 *               &lt;enumeration value="6100"/>
 *               &lt;enumeration value="6371"/>
 *               &lt;enumeration value="3324"/>
 *               &lt;enumeration value="69750"/>
 *               &lt;enumeration value="58170"/>
 *               &lt;enumeration value="23750"/>
 *               &lt;enumeration value="22400"/>
 *               &lt;enumeration value="3000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LENGTH_OF_YEAR">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0.24085"/>
 *               &lt;enumeration value="0.61521"/>
 *               &lt;enumeration value="1.000039"/>
 *               &lt;enumeration value="1.88089"/>
 *               &lt;enumeration value="11.8653"/>
 *               &lt;enumeration value="29.6501"/>
 *               &lt;enumeration value="83.7445"/>
 *               &lt;enumeration value="165.951"/>
 *               &lt;enumeration value="247.687"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DAY">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="88"/>
 *               &lt;enumeration value="230"/>
 *               &lt;enumeration value="24"/>
 *               &lt;enumeration value="24.5"/>
 *               &lt;enumeration value="9.8"/>
 *               &lt;enumeration value="10.2"/>
 *               &lt;enumeration value="10.7"/>
 *               &lt;enumeration value="12.7"/>
 *               &lt;enumeration value="6.39"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MASS">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0.054"/>
 *               &lt;enumeration value="0.814"/>
 *               &lt;enumeration value="1.00"/>
 *               &lt;enumeration value="0.107"/>
 *               &lt;enumeration value="317.4"/>
 *               &lt;enumeration value="95.0"/>
 *               &lt;enumeration value="14.5"/>
 *               &lt;enumeration value="17.6"/>
 *               &lt;enumeration value="0.2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DENSITY">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="6.03"/>
 *               &lt;enumeration value="5.11"/>
 *               &lt;enumeration value="5.517"/>
 *               &lt;enumeration value="4.16"/>
 *               &lt;enumeration value="1.34"/>
 *               &lt;enumeration value="0.68"/>
 *               &lt;enumeration value="1.55"/>
 *               &lt;enumeration value="2.23"/>
 *               &lt;enumeration value="5.2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SATELLITES" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="63"/>
 *               &lt;enumeration value="61"/>
 *               &lt;enumeration value="27"/>
 *               &lt;enumeration value="13"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="COLOR" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PLANETType", propOrder = {
    "name",
    "distance",
    "radius",
    "lengthofyear",
    "day",
    "mass",
    "density",
    "satellites"
})
public class PLANETType {

    @XmlElement(name = "NAME", required = true)
    protected String name;
    @XmlElement(name = "DISTANCE", required = true)
    protected String distance;
    @XmlElement(name = "RADIUS", required = true)
    protected String radius;
    @XmlElement(name = "LENGTH_OF_YEAR", required = true)
    protected String lengthofyear;
    @XmlElement(name = "DAY", required = true)
    protected String day;
    @XmlElement(name = "MASS", required = true)
    protected String mass;
    @XmlElement(name = "DENSITY", required = true)
    protected String density;
    @XmlElement(name = "SATELLITES")
    protected String satellites;
    @XmlAttribute(name = "COLOR")
    protected String color;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAME(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISTANCE() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISTANCE(String value) {
        this.distance = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRADIUS() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRADIUS(String value) {
        this.radius = value;
    }

    /**
     * Gets the value of the lengthofyear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLENGTHOFYEAR() {
        return lengthofyear;
    }

    /**
     * Sets the value of the lengthofyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLENGTHOFYEAR(String value) {
        this.lengthofyear = value;
    }

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAY() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAY(String value) {
        this.day = value;
    }

    /**
     * Gets the value of the mass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMASS() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMASS(String value) {
        this.mass = value;
    }

    /**
     * Gets the value of the density property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDENSITY() {
        return density;
    }

    /**
     * Sets the value of the density property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDENSITY(String value) {
        this.density = value;
    }

    /**
     * Gets the value of the satellites property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSATELLITES() {
        return satellites;
    }

    /**
     * Sets the value of the satellites property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSATELLITES(String value) {
        this.satellites = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOLOR() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOLOR(String value) {
        this.color = value;
    }

}
